services:
  vite_docker:
    container_name: vite_docker
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
